#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ffmpeg
Version  : n4.2.2
Release  : 1
URL      : https://github.com/FFmpeg/FFmpeg/archive/n4.2.2.tar.gz
Source0  : https://github.com/FFmpeg/FFmpeg/archive/n4.2.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
Requires: ffmpeg-bin = %{version}-%{release}
Requires: ffmpeg-data = %{version}-%{release}
Requires: ffmpeg-lib = %{version}-%{release}
Requires: ffmpeg-man = %{version}-%{release}
BuildRequires : SDL2-dev
BuildRequires : alsa-lib-dev
BuildRequires : appstream-glib-dev
BuildRequires : bzip2-dev
BuildRequires : dav1d-dev
BuildRequires : fdk-aac-dev
BuildRequires : fontconfig-dev
BuildRequires : freetype-dev
BuildRequires : gmp-dev
BuildRequires : gnutls-dev
BuildRequires : gsm-dev
BuildRequires : jack2-dev
BuildRequires : ladspa_sdk-dev
BuildRequires : lame-dev
BuildRequires : libXvMC-dev
BuildRequires : libass-dev
BuildRequires : libdrm-dev
BuildRequires : libgcrypt-devel
BuildRequires : libjpeg-turbo-dev
BuildRequires : libmodplug-dev
BuildRequires : libtheora-dev
BuildRequires : libva-dev
BuildRequires : libvorbis-dev
BuildRequires : libvpx-dev
BuildRequires : libwebp-dev
BuildRequires : mediasdk-dev
BuildRequires : mesa-dev
BuildRequires : nasm
BuildRequires : openssl-dev
BuildRequires : opus-dev
BuildRequires : perl-Pod-POM-man
BuildRequires : pulseaudio-dev
BuildRequires : rtmpdump-dev
BuildRequires : snappy-dev
BuildRequires : speex-dev
BuildRequires : subversion
BuildRequires : texinfo
BuildRequires : v4l-utils-dev
BuildRequires : wavpack-dev
BuildRequires : x264-dev
BuildRequires : x265-dev
BuildRequires : yasm
BuildRequires : zlib-dev
Patch1: 0001-configure-do-not-die-if-unknown-option-is-found.patch

%description
SPARC optimizations have been removed in
commit b4dd424d96f09f9bafb88e47f37df65dc4529143
The last revission with the optimizations is fb1b70c1ed50951c5fc1a309c3c446b2eaaf564b

%package bin
Summary: bin components for the ffmpeg package.
Group: Binaries
Requires: ffmpeg-data = %{version}-%{release}

%description bin
bin components for the ffmpeg package.


%package data
Summary: data components for the ffmpeg package.
Group: Data

%description data
data components for the ffmpeg package.


%package dev
Summary: dev components for the ffmpeg package.
Group: Development
Requires: ffmpeg-lib = %{version}-%{release}
Requires: ffmpeg-bin = %{version}-%{release}
Requires: ffmpeg-data = %{version}-%{release}
Provides: ffmpeg-devel = %{version}-%{release}
Requires: ffmpeg = %{version}-%{release}

%description dev
dev components for the ffmpeg package.


%package doc
Summary: doc components for the ffmpeg package.
Group: Documentation
Requires: ffmpeg-man = %{version}-%{release}

%description doc
doc components for the ffmpeg package.


%package lib
Summary: lib components for the ffmpeg package.
Group: Libraries
Requires: ffmpeg-data = %{version}-%{release}

%description lib
lib components for the ffmpeg package.


%package man
Summary: man components for the ffmpeg package.
Group: Default

%description man
man components for the ffmpeg package.


%prep
%setup -q -n FFmpeg-n4.2.2
cd %{_builddir}/FFmpeg-n4.2.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1586688930
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static --enable-avfilter \
--enable-avresample \
--enable-bzlib \
--enable-fontconfig \
--enable-gcrypt \
--enable-gmp \
--enable-gnutls \
--enable-gpl \
--enable-ladspa \
--enable-libass \
--enable-libdav1d \
--enable-libdrm \
--enable-libfdk-aac \
--enable-libfdk-aac \
--enable-libfreetype \
--enable-libfribidi \
--enable-libgsm \
--enable-libjack \
--enable-libmfx \
--enable-libmp3lame \
--enable-libopus \
--enable-libpulse \
--enable-librtmp \
--enable-libsnappy \
--enable-libspeex \
--enable-libv4l2 \
--enable-libvorbis \
--enable-libvpx \
--enable-libwebp \
--enable-libx264 \
--enable-libx265 \
--enable-nonfree \
--enable-nonfree \
--enable-opengl \
--enable-postproc \
--enable-pthreads \
--enable-shared \
--enable-vaapi \
--enable-version3 \
--extra-ldflags='-ldl'
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1586688930
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ffmpeg
/usr/bin/ffplay
/usr/bin/ffprobe

%files data
%defattr(-,root,root,-)
/usr/share/examples/Makefile
/usr/share/examples/README
/usr/share/examples/avio_dir_cmd.c
/usr/share/examples/avio_reading.c
/usr/share/examples/decode_audio.c
/usr/share/examples/decode_video.c
/usr/share/examples/demuxing_decoding.c
/usr/share/examples/encode_audio.c
/usr/share/examples/encode_video.c
/usr/share/examples/extract_mvs.c
/usr/share/examples/filter_audio.c
/usr/share/examples/filtering_audio.c
/usr/share/examples/filtering_video.c
/usr/share/examples/http_multiclient.c
/usr/share/examples/hw_decode.c
/usr/share/examples/metadata.c
/usr/share/examples/muxing.c
/usr/share/examples/qsvdec.c
/usr/share/examples/remuxing.c
/usr/share/examples/resampling_audio.c
/usr/share/examples/scaling_video.c
/usr/share/examples/transcode_aac.c
/usr/share/examples/transcoding.c
/usr/share/examples/vaapi_encode.c
/usr/share/examples/vaapi_transcode.c
/usr/share/ffprobe.xsd
/usr/share/libvpx-1080p.ffpreset
/usr/share/libvpx-1080p50_60.ffpreset
/usr/share/libvpx-360p.ffpreset
/usr/share/libvpx-720p.ffpreset
/usr/share/libvpx-720p50_60.ffpreset

%files dev
%defattr(-,root,root,-)
/usr/include/libavcodec/ac3_parser.h
/usr/include/libavcodec/adts_parser.h
/usr/include/libavcodec/avcodec.h
/usr/include/libavcodec/avdct.h
/usr/include/libavcodec/avfft.h
/usr/include/libavcodec/d3d11va.h
/usr/include/libavcodec/dirac.h
/usr/include/libavcodec/dv_profile.h
/usr/include/libavcodec/dxva2.h
/usr/include/libavcodec/jni.h
/usr/include/libavcodec/mediacodec.h
/usr/include/libavcodec/qsv.h
/usr/include/libavcodec/vaapi.h
/usr/include/libavcodec/vdpau.h
/usr/include/libavcodec/version.h
/usr/include/libavcodec/videotoolbox.h
/usr/include/libavcodec/vorbis_parser.h
/usr/include/libavcodec/xvmc.h
/usr/include/libavdevice/avdevice.h
/usr/include/libavdevice/version.h
/usr/include/libavfilter/avfilter.h
/usr/include/libavfilter/buffersink.h
/usr/include/libavfilter/buffersrc.h
/usr/include/libavfilter/version.h
/usr/include/libavformat/avformat.h
/usr/include/libavformat/avio.h
/usr/include/libavformat/version.h
/usr/include/libavresample/avresample.h
/usr/include/libavresample/version.h
/usr/include/libavutil/adler32.h
/usr/include/libavutil/aes.h
/usr/include/libavutil/aes_ctr.h
/usr/include/libavutil/attributes.h
/usr/include/libavutil/audio_fifo.h
/usr/include/libavutil/avassert.h
/usr/include/libavutil/avconfig.h
/usr/include/libavutil/avstring.h
/usr/include/libavutil/avutil.h
/usr/include/libavutil/base64.h
/usr/include/libavutil/blowfish.h
/usr/include/libavutil/bprint.h
/usr/include/libavutil/bswap.h
/usr/include/libavutil/buffer.h
/usr/include/libavutil/camellia.h
/usr/include/libavutil/cast5.h
/usr/include/libavutil/channel_layout.h
/usr/include/libavutil/common.h
/usr/include/libavutil/cpu.h
/usr/include/libavutil/crc.h
/usr/include/libavutil/des.h
/usr/include/libavutil/dict.h
/usr/include/libavutil/display.h
/usr/include/libavutil/downmix_info.h
/usr/include/libavutil/encryption_info.h
/usr/include/libavutil/error.h
/usr/include/libavutil/eval.h
/usr/include/libavutil/ffversion.h
/usr/include/libavutil/fifo.h
/usr/include/libavutil/file.h
/usr/include/libavutil/frame.h
/usr/include/libavutil/hash.h
/usr/include/libavutil/hdr_dynamic_metadata.h
/usr/include/libavutil/hmac.h
/usr/include/libavutil/hwcontext.h
/usr/include/libavutil/hwcontext_cuda.h
/usr/include/libavutil/hwcontext_d3d11va.h
/usr/include/libavutil/hwcontext_drm.h
/usr/include/libavutil/hwcontext_dxva2.h
/usr/include/libavutil/hwcontext_mediacodec.h
/usr/include/libavutil/hwcontext_qsv.h
/usr/include/libavutil/hwcontext_vaapi.h
/usr/include/libavutil/hwcontext_vdpau.h
/usr/include/libavutil/hwcontext_videotoolbox.h
/usr/include/libavutil/imgutils.h
/usr/include/libavutil/intfloat.h
/usr/include/libavutil/intreadwrite.h
/usr/include/libavutil/lfg.h
/usr/include/libavutil/log.h
/usr/include/libavutil/lzo.h
/usr/include/libavutil/macros.h
/usr/include/libavutil/mastering_display_metadata.h
/usr/include/libavutil/mathematics.h
/usr/include/libavutil/md5.h
/usr/include/libavutil/mem.h
/usr/include/libavutil/motion_vector.h
/usr/include/libavutil/murmur3.h
/usr/include/libavutil/opt.h
/usr/include/libavutil/parseutils.h
/usr/include/libavutil/pixdesc.h
/usr/include/libavutil/pixelutils.h
/usr/include/libavutil/pixfmt.h
/usr/include/libavutil/random_seed.h
/usr/include/libavutil/rational.h
/usr/include/libavutil/rc4.h
/usr/include/libavutil/replaygain.h
/usr/include/libavutil/ripemd.h
/usr/include/libavutil/samplefmt.h
/usr/include/libavutil/sha.h
/usr/include/libavutil/sha512.h
/usr/include/libavutil/spherical.h
/usr/include/libavutil/stereo3d.h
/usr/include/libavutil/tea.h
/usr/include/libavutil/threadmessage.h
/usr/include/libavutil/time.h
/usr/include/libavutil/timecode.h
/usr/include/libavutil/timestamp.h
/usr/include/libavutil/tree.h
/usr/include/libavutil/twofish.h
/usr/include/libavutil/tx.h
/usr/include/libavutil/version.h
/usr/include/libavutil/xtea.h
/usr/include/libpostproc/postprocess.h
/usr/include/libpostproc/version.h
/usr/include/libswresample/swresample.h
/usr/include/libswresample/version.h
/usr/include/libswscale/swscale.h
/usr/include/libswscale/version.h
/usr/lib64/libavcodec.so
/usr/lib64/libavdevice.so
/usr/lib64/libavfilter.so
/usr/lib64/libavformat.so
/usr/lib64/libavresample.so
/usr/lib64/libavutil.so
/usr/lib64/libpostproc.so
/usr/lib64/libswresample.so
/usr/lib64/libswscale.so
/usr/lib64/pkgconfig/libavcodec.pc
/usr/lib64/pkgconfig/libavdevice.pc
/usr/lib64/pkgconfig/libavfilter.pc
/usr/lib64/pkgconfig/libavformat.pc
/usr/lib64/pkgconfig/libavresample.pc
/usr/lib64/pkgconfig/libavutil.pc
/usr/lib64/pkgconfig/libpostproc.pc
/usr/lib64/pkgconfig/libswresample.pc
/usr/lib64/pkgconfig/libswscale.pc
/usr/share/man/man3/libavcodec.3
/usr/share/man/man3/libavdevice.3
/usr/share/man/man3/libavfilter.3
/usr/share/man/man3/libavformat.3
/usr/share/man/man3/libavutil.3
/usr/share/man/man3/libswresample.3
/usr/share/man/man3/libswscale.3

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/ffmpeg/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libavcodec.so.58
/usr/lib64/libavcodec.so.58.54.100
/usr/lib64/libavdevice.so.58
/usr/lib64/libavdevice.so.58.8.100
/usr/lib64/libavfilter.so.7
/usr/lib64/libavfilter.so.7.57.100
/usr/lib64/libavformat.so.58
/usr/lib64/libavformat.so.58.29.100
/usr/lib64/libavresample.so.4
/usr/lib64/libavresample.so.4.0.0
/usr/lib64/libavutil.so.56
/usr/lib64/libavutil.so.56.31.100
/usr/lib64/libpostproc.so.55
/usr/lib64/libpostproc.so.55.5.100
/usr/lib64/libswresample.so.3
/usr/lib64/libswresample.so.3.5.100
/usr/lib64/libswscale.so.5
/usr/lib64/libswscale.so.5.5.100

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ffmpeg-all.1
/usr/share/man/man1/ffmpeg-bitstream-filters.1
/usr/share/man/man1/ffmpeg-codecs.1
/usr/share/man/man1/ffmpeg-devices.1
/usr/share/man/man1/ffmpeg-filters.1
/usr/share/man/man1/ffmpeg-formats.1
/usr/share/man/man1/ffmpeg-protocols.1
/usr/share/man/man1/ffmpeg-resampler.1
/usr/share/man/man1/ffmpeg-scaler.1
/usr/share/man/man1/ffmpeg-utils.1
/usr/share/man/man1/ffmpeg.1
/usr/share/man/man1/ffplay-all.1
/usr/share/man/man1/ffplay.1
/usr/share/man/man1/ffprobe-all.1
/usr/share/man/man1/ffprobe.1
